### ISSUE TITLE
ImportError: libopencv_core.so.3.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Myzhencai** [fehlfarbe/python-aruco#23]
@fehlfarbe  i installed everything successfully with no warning and bug but even through i have done : export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH
i still get this error .can you help me out ,please.

Python 3.4.3 (default, Nov 28 2017, 16:41:13) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aruco
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/aruco.py", line 28, in <module>
    _aruco = swig_import_helper()
  File "/usr/local/lib/python3.4/dist-packages/aruco.py", line 24, in swig_import_helper
    _mod = imp.load_module('_aruco', fp, pathname, description)
  File "/usr/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
ImportError: libopencv_core.so.3.4: cannot open shared object file: No such file or directory
>>> 

python-aruco 1.3.0 opencv3.4.0 numpy 1.9.0
the way i install opencv is : (python3.4 as default)
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D BUILD_NEW_PYTHON_SUPPORT=ON -D PYTHON_EXECUTABLE=$(which python3) ..
any information should i provide please ask, thanks

**Comment by Myzhencai** [comment]
this issue can be when you cmake the opencv you did not have the python-library_path set down ,it might need to sudo apt-get install python-dev(python3-dev)
