### ISSUE TITLE
Issue when cross-compiling to arm

### ISSUE THREAD

**Issue by petergerten** [fehlfarbe/python-aruco#35]
For cross-compiling I adjusted the include directories in setup.py and could build everything.
On import aruco I get the following error though:

```
>>> import aruco
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/aruco.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 938, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: /usr/lib/python3.5/site-packages/_aruco.cpython-35m-arm-linux-gnueabihf.so: undefined symbol: _ZN2cv19FastFeatureDetector6createEibi

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/aruco.py", line 17, in <module>
    _aruco = swig_import_helper()
  File "/usr/lib/python3.5/site-packages/aruco.py", line 16, in swig_import_helper
    return importlib.import_module('_aruco')
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /usr/lib/python3.5/site-packages/_aruco.cpython-35m-arm-linux-gnueabihf.so: undefined symbol: _ZN2cv19FastFeatureDetector6createEibi
```

Does anyone have a pointer on what went wrong here?

**Comment by fehlfarbe** [comment]
Can you please check the built .so with `ldd _aruco.cpython-35m-arm-linux-gnueabihf.so` and also with `nm _aruco.cpython-35m-arm-linux-gnueabihf.so`. What OpenCV version did you install?

**Comment by petergerten** [comment]
I use OpenCV 3.4.3
This is the ldd output:
```
        linux-vdso.so.1 (0x7edc6000)
        libopencv_core.so.3.4 => /usr/lib/libopencv_core.so.3.4 (0x76ce6000)
        libopencv_imgproc.so.3.4 => /usr/lib/libopencv_imgproc.so.3.4 (0x76a76000)
        libopencv_calib3d.so.3.4 => /usr/lib/libopencv_calib3d.so.3.4 (0x7698f000)
        libopencv_highgui.so.3.4 => /usr/lib/libopencv_highgui.so.3.4 (0x76977000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7686d000)
        libm.so.6 => /lib/libm.so.6 (0x767f5000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x767cb000)
        libc.so.6 => /lib/libc.so.6 (0x766d8000)
        /lib/ld-linux-armhf.so.3 (0x76f7f000)
        libpthread.so.0 => /lib/libpthread.so.0 (0x766b4000)
        librt.so.1 => /lib/librt.so.1 (0x7669e000)
        libz.so.1 => /lib/libz.so.1 (0x7667e000)
        libopencv_flann.so.3.4 => /usr/lib/libopencv_flann.so.3.4 (0x76637000)
```
I currently don't have `nm` on my target - will check if I can get it on.

**Comment by fehlfarbe** [comment]
Can you add `opencv_feactures2d` in setup.py and recompile?

Just replace

`libraries=["opencv_core", "opencv_imgproc", "opencv_calib3d", "opencv_highgui", "opencv_ml"],`
 with
`libraries=["opencv_core", "opencv_imgproc", "opencv_calib3d", "opencv_highgui", "opencv_ml", "opencv_feactures2d"],`

in

https://github.com/fehlfarbe/python-aruco/blob/master/setup.py#L33

**Comment by petergerten** [comment]
@fehlfarbe thanks a lot - that solved it!
